const SUPABASE_URL="https://deosivmmboovramgwuft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_WsnQdEgCb6YTLdeTmdt3hA_mDfs5eA4";
const {createClient}=supabase;
const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
let currentUser=null,currentProfile=null;

function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
function money(v){return Number(v||0)===0?"Free":"₹"+Number(v).toLocaleString("en-IN");}
function openModal(html){document.getElementById("modalContent").innerHTML=html;document.getElementById("modal").classList.add("show");}
function closeModal(){document.getElementById("modal").classList.remove("show");}
function openAuth(){openModal(`<h2>Login / Signup</h2><input id="authName" placeholder="Full name (signup के लिए)"><input id="authEmail" type="email" placeholder="Email"><input id="authPassword" type="password" placeholder="Password"><div class="row"><button class="primaryBtn" onclick="signIn()">Login</button><button class="secondaryBtn" onclick="signUp()">Signup</button></div><p id="authMsg" class="muted"></p>`);}
async function signUp(){const name=authName.value.trim(),email=authEmail.value.trim(),password=authPassword.value,msg=authMsg;if(!name||!email||password.length<6){msg.textContent="Name, email और कम-से-कम 6 character password भरें.";return}const {error}=await db.auth.signUp({email,password,options:{data:{full_name:name}}});msg.textContent=error?error.message:"Signup हो गया. Email confirmation on हो तो पहले email verify करें.";}
async function signIn(){const email=authEmail.value.trim(),password=authPassword.value,msg=authMsg;const {error}=await db.auth.signInWithPassword({email,password});if(error){msg.textContent=error.message;return}closeModal();await refreshSession();}
async function logout(){await db.auth.signOut();await refreshSession();}
async function refreshSession(){const {data:{session}}=await db.auth.getSession();currentUser=session?.user||null;const btn=document.getElementById("authBtn");btn.textContent=currentUser?"Logout":"Login";btn.onclick=currentUser?logout:openAuth;if(currentUser){const {data}=await db.from("profiles").select("*").eq("id",currentUser.id).single();currentProfile=data||null;}else currentProfile=null;document.getElementById("dashboard").classList.toggle("hidden",!currentUser);document.getElementById("admin").classList.toggle("hidden",currentProfile?.role!=="admin");if(currentUser)await renderDashboard();if(currentProfile?.role==="admin")await renderAdmin();}

async function loadCourses(){const {data,error}=await db.from("courses").select("*").eq("is_published",true).order("created_at",{ascending:false});const el=document.getElementById("coursesGrid");if(error){el.innerHTML=`<div class="card error">${esc(error.message)}</div>`;return}el.innerHTML=data?.length?data.map(c=>`<div class="card">${c.thumbnail_url?`<img class="thumb" src="${esc(c.thumbnail_url)}" alt="">`:""}<h3>${esc(c.title)}</h3><p class="muted">${esc(c.description||"")}</p><div class="price">${money(c.price)}</div><div class="row"><button class="primaryBtn" onclick="enroll('${c.id}')">Enroll</button><button class="secondaryBtn" onclick="openCourse('${c.id}')">View Course</button></div></div>`).join(""):`<div class="card"><h3>अभी courses नहीं हैं</h3><p>Admin panel से पहला course add करें.</p></div>`;}
async function loadTests(){const {data,error}=await db.from("tests").select("*").eq("is_published",true).order("created_at",{ascending:false});const el=document.getElementById("testsGrid");if(error){el.innerHTML=`<div class="card error">${esc(error.message)}</div>`;return}el.innerHTML=data?.length?data.map(t=>`<div class="card"><h3>${esc(t.title)}</h3><p class="muted">${esc(t.description||"")}</p><p>⏱️ ${t.duration_minutes} मिनट</p><button class="primaryBtn" onclick="startTest('${t.id}')">Start Test</button></div>`).join(""):`<div class="card"><h3>अभी tests नहीं हैं</h3></div>`;}

async function enroll(courseId){if(!currentUser){openAuth();return}const {error}=await db.from("enrollments").upsert({user_id:currentUser.id,course_id:courseId,status:"active"},{onConflict:"user_id,course_id"});if(error){alert(error.message);return}alert("Course enrollment सफल रहा!");await renderDashboard();await openCourse(courseId);}
async function renderDashboard(){document.getElementById("profileBox").innerHTML=`<h3>नमस्ते, ${esc(currentProfile?.full_name||currentUser.email)}</h3><p>${esc(currentUser.email)}</p><p>Role: ${esc(currentProfile?.role||"student")}</p><button class="danger" onclick="logout()">Logout</button>`;const {data}=await db.from("enrollments").select("id,status,enrolled_at,courses(title,description,price)").eq("user_id",currentUser.id).order("enrolled_at",{ascending:false});document.getElementById("enrollmentsGrid").innerHTML=data?.length?data.map(e=>`<div class="card"><h3>${esc(e.courses?.title||"Course")}</h3><p>${esc(e.courses?.description||"")}</p><p class="success">Status: ${esc(e.status)}</p></div>`).join(""):`<div class="card"><p>अभी कोई enrolled course नहीं है.</p></div>`;}

async function openCourse(courseId){
 const {data:course,error:ce}=await db.from("courses").select("id,title,description,price").eq("id",courseId).single();
 if(ce){alert(ce.message);return;}
 if(!currentUser){openModal(`<h2>${esc(course.title)}</h2><p>${esc(course.description||"")}</p><p class="price">${money(course.price)}</p><p>Lessons देखने के लिए पहले Login करें और course में Enroll करें.</p><button class="primaryBtn" onclick="closeModal();openAuth()">Login / Signup</button>`);return;}
 const {data:en}=await db.from("enrollments").select("id,status").eq("user_id",currentUser.id).eq("course_id",courseId).maybeSingle();
 if(!en || en.status!=="active"){openModal(`<h2>${esc(course.title)}</h2><p>${esc(course.description||"")}</p><p class="price">${money(course.price)}</p><p>यह course देखने के लिए पहले Enroll करें.</p><button class="primaryBtn" onclick="closeModal();enroll('${courseId}')">Enroll Now</button>`);return;}
 const {data:lessons,error}=await db.from("lessons").select("id,title,description,video_url,pdf_url,sort_order").eq("course_id",courseId).eq("is_published",true).order("sort_order",{ascending:true});
 if(error){alert(error.message);return;}
 openModal(`<h2>${esc(course.title)}</h2><p class="muted">${esc(course.description||"")}</p><div class="lessonList">${lessons?.length?lessons.map((l,i)=>`<div class="lesson"><div><strong>${i+1}. ${esc(l.title)}</strong><p>${esc(l.description||"")}</p></div><div class="row">${l.video_url?`<button class="secondaryBtn" onclick="playVideo(${JSON.stringify(l.video_url)},${JSON.stringify(l.title)})">▶ Video</button>`:""}${l.pdf_url?`<a class="secondaryBtn linkBtn" target="_blank" rel="noopener" href="${esc(l.pdf_url)}">📄 PDF</a>`:""}</div></div>`).join(""):`<div class="card"><p>इस course में अभी lessons publish नहीं हुए हैं.</p></div>`}</div>`);
}
function playVideo(url,title){let embed=url;if(/youtube\.com\/watch\?v=|youtu\.be\//i.test(url)){const m=url.match(/(?:v=|youtu\.be\/)([A-Za-z0-9_-]{6,})/i);if(m)embed=`https://www.youtube.com/embed/${m[1]}`;}openModal(`<h2>${esc(title)}</h2><div class="videoWrap"><iframe src="${esc(embed)}" title="${esc(title)}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><p class="muted small">Video source: ${esc(url)}</p>`);}

async function refreshLessonCourses(){const {data}=await db.from("courses").select("id,title").order("created_at",{ascending:false});const sel=document.getElementById("lessonCourse");if(!sel)return;sel.innerHTML=`<option value="">Course चुनें</option>`+(data||[]).map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join("");}
async function renderAdmin(){await refreshLessonCourses();const {data,error}=await db.from("courses").select("id,title,price,is_published,lessons(id,title,is_published,sort_order)").order("created_at",{ascending:false});const el=document.getElementById("adminCourses");if(error){el.innerHTML=`<div class="card error">${esc(error.message)}</div>`;return}el.innerHTML=(data||[]).map(c=>`<div class="card"><h3>${esc(c.title)}</h3><p>${money(c.price)} • ${c.is_published?"Published":"Draft"}</p><p><b>${(c.lessons||[]).length}</b> lessons</p>${(c.lessons||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(l=>`<div class="miniLesson">${esc(l.title)} <span>${l.is_published?"Published":"Draft"}</span></div>`).join("")||`<p class="muted">अभी कोई lesson नहीं.</p>`}</div>`).join("")||`<div class="card">No courses yet.</div>`;}

document.getElementById("courseForm").addEventListener("submit",async e=>{e.preventDefault();const {error}=await db.from("courses").insert({title:courseTitle.value.trim(),description:courseDesc.value.trim(),price:Number(coursePrice.value||0),thumbnail_url:courseThumb.value.trim()||null,is_published:coursePublished.checked});if(error){alert(error.message);return}e.target.reset();coursePrice.value=0;await loadCourses();await renderAdmin();alert("Course added successfully!");});
document.getElementById("lessonForm").addEventListener("submit",async e=>{e.preventDefault();const {error}=await db.from("lessons").insert({course_id:lessonCourse.value,title:lessonTitle.value.trim(),description:lessonDesc.value.trim(),video_url:lessonVideo.value.trim()||null,pdf_url:lessonPdf.value.trim()||null,sort_order:Number(lessonOrder.value||0),is_published:lessonPublished.checked});if(error){alert(error.message);return}e.target.reset();lessonOrder.value=1;await renderAdmin();alert("Lesson added successfully!");});
document.getElementById("testForm").addEventListener("submit",async e=>{e.preventDefault();const {error}=await db.from("tests").insert({title:testTitle.value.trim(),description:testDesc.value.trim(),duration_minutes:Number(testDuration.value||30),is_published:testPublished.checked});if(error){alert(error.message);return}e.target.reset();testDuration.value=30;await loadTests();alert("Test added successfully!");});

async function startTest(testId){if(!currentUser){openAuth();return}const {data,error}=await db.from("test_questions").select("id,question,option_a,option_b,option_c,option_d").eq("test_id",testId).order("sort_order");if(error){alert(error.message);return}if(!data?.length){alert("इस test में अभी questions नहीं हैं.");return}let i=0,answers=[];function show(){const q=data[i];openModal(`<h2>Question ${i+1}/${data.length}</h2><p><b>${esc(q.question)}</b></p>${["A","B","C","D"].map(x=>`<label class="option"><input type="radio" name="ans" value="${x}"> ${esc(q["option_"+x.toLowerCase()])}</label>`).join("")}<button class="primaryBtn" onclick="nextQ()">${i===data.length-1?"Submit":"Next"}</button>`);}window.nextQ=function(){const picked=document.querySelector('input[name="ans"]:checked');if(!picked){alert("एक option चुनें.");return}answers.push({question_id:data[i].id,selected_option:picked.value});i++;if(i<data.length)show();else submitAttempt(testId,answers,data.length);};show();}
async function submitAttempt(testId,answers,total){const {data:attempt,error}=await db.from("test_attempts").insert({test_id:testId,user_id:currentUser.id,total_questions:total}).select().single();if(error){alert(error.message);return}const {data:questions}=await db.from("test_questions").select("id,correct_option").in("id",answers.map(a=>a.question_id));let score=0;const rows=answers.map(a=>{const q=questions.find(x=>x.id===a.question_id);const ok=q?.correct_option===a.selected_option;if(ok)score++;return {...a,attempt_id:attempt.id,is_correct:ok};});const {error:ae}=await db.from("test_answers").insert(rows);if(ae){alert(ae.message);return}await db.from("test_attempts").update({score,submitted_at:new Date().toISOString()}).eq("id",attempt.id);openModal(`<h2>Test Submitted 🎉</h2><p>Your score: <b>${score}/${total}</b></p><button class="primaryBtn" onclick="closeModal()">Close</button>`);}

db.auth.onAuthStateChange(()=>refreshSession());
(async()=>{document.getElementById("connectionStatus").textContent="Supabase connected • Real database";await loadCourses();await loadTests();await refreshSession();})();
